package main

import (
	"fmt"
	"strings"
	"testing"
)

func TestExclusionManifestRequiresExactTrackedKinds(t *testing.T) {
	manifest := exclusionManifest{SchemaVersion: 1, Entries: []exclusionEntry{
		{Path: "harness/internal/generated.go", Kind: exclusionGenerated, Reason: "generated protocol projection", Owner: "model"},
		{Path: "harness/internal/testdata/fixture.go", Kind: exclusionTestdata, Reason: "parser fixture", Owner: "testkit"},
	}}
	if err := validateExclusionManifest(manifest); err != nil {
		t.Fatal(err)
	}
	manifest.Entries[1].Path = "harness/internal/zfixture.go"
	if err := validateExclusionManifest(manifest); err == nil || !strings.Contains(err.Error(), "not inside testdata") {
		t.Fatalf("testdata path error = %v", err)
	}
}

func TestExclusionManifestIsOptionalForMeasurementButRequiredForRepositoryCheck(t *testing.T) {
	root := t.TempDir()
	manifest, err := loadQualityExclusions(root, false)
	if err != nil || manifest.SchemaVersion != 1 || len(manifest.Entries) != 0 {
		t.Fatalf("optional exclusion manifest = %#v, error = %v", manifest, err)
	}
	if _, err := loadQualityExclusions(root, true); err == nil || !strings.Contains(err.Error(), "go_quality_exclusions.json") {
		t.Fatalf("required exclusion error = %v", err)
	}
	writeTestFile(t, root, exclusionsPath, "{\"schema_version\":1,\"entries\":[]}")
	if _, err := loadQualityExclusions(root, true); err == nil || !strings.Contains(err.Error(), "canonical") {
		t.Fatalf("noncanonical exclusion error = %v", err)
	}
}

func TestExclusionEvidenceRejectsForgedGeneratedClassification(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, root, "harness/forged.go", "package harness\nconst text = `Code generated DO NOT EDIT.`\n")
	manifest := exclusionManifest{SchemaVersion: 1, Entries: []exclusionEntry{{
		Path: "harness/forged.go", Kind: exclusionGenerated, Reason: "claimed generated", Owner: "test",
	}}}
	if err := validateExclusionEvidence(root, manifest); err == nil || !strings.Contains(err.Error(), "canonical generated header") {
		t.Fatalf("forged generated evidence error = %v", err)
	}
}

func TestGeneratedMetricExclusionDoesNotHideNolintOrDependencies(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, root, "harness/internal/store/generated.go", `// Code generated by fixture. DO NOT EDIT.
package store

import _ "github.com/mnemon-dev/mnemon/harness/internal/teamwork"

//nolint
func generated() {}
`)
	writeCanonicalTestFile(t, root, exclusionsPath, exclusionManifest{SchemaVersion: 1, Entries: []exclusionEntry{{
		Path: "harness/internal/store/generated.go", Kind: exclusionGenerated, Reason: "generated fixture", Owner: "test",
	}}})
	files, err := loadHarnessSources(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(metricEligibleSources(files)) != 0 {
		t.Fatalf("generated file remained metric eligible: %#v", sourcePaths(files))
	}
	if diagnostics := nolintDiagnostics(files); len(diagnostics) != 1 {
		t.Fatalf("generated nolint diagnostics = %#v", diagnostics)
	}
	findings, err := dependencyFindings(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(findings) != 1 || findings[0].Rule != "dependency_direction" {
		t.Fatalf("generated dependency findings = %#v", findings)
	}
}

func TestCanonicalHeaderAloneCannotHideMeasuredDebt(t *testing.T) {
	root := t.TempDir()
	var source strings.Builder
	source.WriteString("// Code generated by fixture. DO NOT EDIT.\npackage harness\n")
	for index := 0; index < 410; index++ {
		fmt.Fprintln(&source, "// measured")
	}
	writeTestFile(t, root, "harness/generated.go", source.String())
	manifest, err := measureTree(root, strings.Repeat("a", 40))
	if err != nil {
		t.Fatal(err)
	}
	want := fileIdentity(ruleProductionFile, "harness/generated.go")
	for _, entry := range manifest.Entries {
		if entry.Identity == want {
			return
		}
	}
	t.Fatalf("header-only generated source did not produce %s: %#v", want, manifest.Entries)
}
