package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestLoadHarnessSourcesUsesExplicitMetricExclusions(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, root, "harness/kept.go", "package harness\nfunc kept() {}\n")
	writeTestFile(t, root, "harness/kept_test.go", "package harness\nfunc TestKept() {}\n")
	writeTestFile(t, root, "harness/generated.go", "// Code generated by fixture. DO NOT EDIT.\npackage harness\n")
	writeTestFile(t, root, "harness/testdata/ignored.go", "package ignored\n")
	writeTestFile(t, root, "harness/.projection/ignored.go", "package ignored\n")
	writeCanonicalTestFile(t, root, exclusionsPath, exclusionManifest{SchemaVersion: 1, Entries: []exclusionEntry{
		{Path: "harness/generated.go", Kind: exclusionGenerated, Reason: "generated fixture", Owner: "test"},
		{Path: "harness/testdata/ignored.go", Kind: exclusionTestdata, Reason: "parser fixture", Owner: "test"},
	}})

	files, err := loadHarnessSources(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 4 {
		t.Fatalf("loaded paths = %#v", sourcePaths(files))
	}
	eligible := metricEligibleSources(files)
	if len(eligible) != 2 || eligible[0].Path != "harness/kept.go" || eligible[1].Path != "harness/kept_test.go" {
		t.Fatalf("metric paths = %#v", sourcePaths(eligible))
	}
	if eligible[0].LineCount != 2 || !eligible[1].IsTest {
		t.Fatalf("source metadata = %#v / %#v", eligible[0], eligible[1])
	}
}

func TestGeneratedAndTestdataSourcesAreIncludedWithoutManifestEntries(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, root, "harness/generated.go", "// Code generated by fixture. DO NOT EDIT.\npackage harness\n")
	writeTestFile(t, root, "harness/testdata/fixture.go", "package fixture\n")
	files, err := loadHarnessSources(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 2 || len(metricEligibleSources(files)) != 2 {
		t.Fatalf("unmanifested sources were hidden: %#v", sourcePaths(files))
	}
}

func TestGeneratedDetectionRequiresCanonicalHeaderBeforePackage(t *testing.T) {
	if !isGeneratedSource([]byte("// Code generated by fixture. DO NOT EDIT.\npackage generated\n")) {
		t.Fatal("canonical generated header was not detected")
	}
	spoof := []byte("package harness\nconst text = `// Code generated by fixture. DO NOT EDIT.`\n")
	if isGeneratedSource(spoof) {
		t.Fatal("generated phrase in source content was trusted")
	}
	blockSpoof := []byte("/*\n// Code generated by fixture. DO NOT EDIT.\n*/\npackage harness\n")
	if isGeneratedSource(blockSpoof) {
		t.Fatal("line-shaped text inside a block comment was trusted as a generated directive")
	}
}

func TestNolintDiagnosticsRequireExactLintAndReason(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, root, "harness/a.go", `package harness
//nolint:errcheck -- lock is released again on close
func Good() {}
//nolint:gosec // test fixture uses a fixed credential
func AlsoGood() {}
//nolint
func Bare() {}
//nolint:all -- blanket waiver
func Wildcard() {}
//nolint:errcheck
func Unexplained() {}
`)
	files, err := loadHarnessSources(root)
	if err != nil {
		t.Fatal(err)
	}
	diagnostics := nolintDiagnostics(files)
	if len(diagnostics) != 3 {
		t.Fatalf("diagnostics = %#v", diagnostics)
	}
}

func TestDependencyFindingsIgnoreHiddenLocalTrees(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, root, ".mnemon-local/bad.go", `package local
import _ "github.com/mnemon-dev/mnemon/harness/internal/store"
`)
	writeTestFile(t, root, "harness/.projection/bad.go", `package projection
import _ "github.com/mnemon-dev/mnemon/internal/store"
`)
	findings, err := dependencyFindings(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(findings) != 0 {
		t.Fatalf("hidden local findings = %#v", findings)
	}
}

func TestSourceScansExcludeNonhiddenGitignoredGo(t *testing.T) {
	root := initTestRepository(t)
	writeTestFile(t, root, ".gitignore", "scratch/\n")
	writeTestFile(t, root, "harness/kept.go", "package harness\n")
	writeTestFile(t, root, "harness/scratch/ignored.go", `package scratch
import _ "github.com/mnemon-dev/mnemon/internal/store"
`)
	files, err := loadHarnessSources(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 1 || files[0].Path != "harness/kept.go" {
		t.Fatalf("files = %#v", sourcePaths(files))
	}
	findings, err := dependencyFindings(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(findings) != 0 {
		t.Fatalf("ignored findings = %#v", findings)
	}
}

func TestRepositoryGoScopePrunesIgnoredDirectoryBeforeTraversal(t *testing.T) {
	root := initTestRepository(t)
	writeTestFile(t, root, ".gitignore", "scratch/\n")
	writeTestFile(t, root, "harness/kept.go", "package harness\n")
	if _, err := os.Stat(filepath.Join(root, "harness", "scratch")); !os.IsNotExist(err) {
		t.Fatalf("scratch precondition: %v", err)
	}
	scope := loadRepositoryGoScope(root)
	ignored := filepath.Join(root, "harness", "scratch")
	if !skipRepositoryDirectory(root, ignored, "scratch", scope) {
		t.Fatal("gitignored directory was left traversable despite having no candidate Go path")
	}
}

func TestGofmtDriftAndDependencyDirection(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, root, "harness/internal/teamwork/good.go", "package teamwork\n\nimport \"github.com/mnemon-dev/mnemon/harness/internal/model\"\n")
	writeTestFile(t, root, "harness/internal/teamwork/good_test.go", "package teamwork\n")
	writeTestFile(t, root, "harness/internal/teamwork/bad.go", "package teamwork\nimport \"github.com/mnemon-dev/mnemon/internal/model\"\n")
	writeTestFile(t, root, "cmd/bad.go", "package cmd\nimport \"github.com/mnemon-dev/mnemon/harness/internal/model\"\n")
	files, err := loadHarnessSources(root)
	if err != nil {
		t.Fatal(err)
	}
	drift, err := gofmtDrift(files)
	if err != nil {
		t.Fatal(err)
	}
	if len(drift) != 1 || drift[0] != "harness/internal/teamwork/bad.go" {
		t.Fatalf("gofmt drift = %#v", drift)
	}
	findings, err := dependencyFindings(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(findings) != 2 || !strings.Contains(findings[0].Identity+findings[1].Identity, "root_harness_dependency") {
		t.Fatalf("dependency findings = %#v", findings)
	}
}

func TestDependencyFindingsEnforceFrozenPackageMapAndLibp2pFloor(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, root, "harness/internal/store/bad.go", `package store
import (
	_ "github.com/mnemon-dev/mnemon/harness/internal/event"
	_ "github.com/libp2p/go-libp2p-core/peer"
)
`)
	writeTestFile(t, root, "harness/internal/event/good.go", `package event
import _ "github.com/mnemon-dev/mnemon/harness/internal/teamwork"
`)
	findings, err := dependencyFindings(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(findings) != 2 {
		t.Fatalf("findings = %#v", findings)
	}
	if findings[0].Rule != "dependency_direction" || findings[1].Rule != "deprecated_libp2p_core" {
		t.Fatalf("finding rules = %#v", findings)
	}
}

func TestDependencyFindingsTrackUnexpectedProductionPackageButNotTestImports(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, root, "harness/internal/cli/command.go", `package cli
import _ "github.com/mnemon-dev/mnemon/harness/internal/store"
`)
	writeTestFile(t, root, "harness/internal/store/blackbox_test.go", `package store_test
import _ "github.com/mnemon-dev/mnemon/harness/internal/agent"
`)
	findings, err := dependencyFindings(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(findings) != 1 || findings[0].Rule != "unexpected_harness_package" {
		t.Fatalf("findings = %#v", findings)
	}
}

func TestDependencyFindingsAllowBottomModelAndUsePackageIdentity(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, root, "harness/internal/node/a.go", `package node
import _ "github.com/mnemon-dev/mnemon/harness/internal/model"
`)
	writeTestFile(t, root, "harness/internal/store/a.go", `package store
import _ "github.com/mnemon-dev/mnemon/harness/internal/teamwork"
`)
	writeTestFile(t, root, "harness/internal/store/b.go", `package store
import _ "github.com/mnemon-dev/mnemon/harness/internal/teamwork"
`)
	findings, err := dependencyFindings(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(findings) != 1 {
		t.Fatalf("findings = %#v", findings)
	}
	if findings[0].Identity != "dependency_direction:harness/internal/store::teamwork" || findings[0].Evidence != "harness/internal/store/a.go" {
		t.Fatalf("package-edge finding = %#v", findings[0])
	}
}

func TestDependencyFindingsAllowNeutralAgencyCLILayer(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, root, "harness/cmd/mnemon-harness/main.go", `package main
import _ "github.com/mnemon-dev/mnemon/harness/internal/agencycli"
`)
	writeTestFile(t, root, "harness/internal/agencycli/app.go", `package agencycli
import _ "github.com/mnemon-dev/mnemon/harness/internal/agency"
`)
	findings, err := dependencyFindings(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(findings) != 0 {
		t.Fatalf("neutral Agency CLI dependency findings = %#v", findings)
	}
}

func TestFunctionSymbolIncludesReceiver(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, root, "harness/a.go", "package harness\ntype T struct{}\nfunc (t *T) Run() {}\n")
	files, err := loadHarnessSources(root)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := declaredSymbols(files[0])["(*T).Run"]; !ok {
		t.Fatalf("symbols = %#v", declaredSymbols(files[0]))
	}
}

func writeTestFile(t *testing.T, root, relative, content string) {
	t.Helper()
	path := filepath.Join(root, filepath.FromSlash(relative))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
}

func sourcePaths(files []sourceFile) []string {
	paths := make([]string, len(files))
	for i := range files {
		paths[i] = files[i].Path
	}
	return paths
}
